// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $api_admin_login from "./routes/api/admin/login.ts";
import * as $api_admin_logout from "./routes/api/admin/logout.ts";
import * as $api_admin_reset_init from "./routes/api/admin/reset-init.ts";
import * as $api_admin_members_id_approve from "./routes/api/admin/members/[id]/approve.ts";
import * as $api_admin_prs_id_approve from "./routes/api/admin/prs/[id]/approve.ts";
import * as $api_admin_results_id_approve from "./routes/api/admin/results/[id]/approve.ts";
import * as $api_auth_change_password from "./routes/api/auth/change-password.ts";
import * as $api_auth_login from "./routes/api/auth/login.ts";
import * as $api_auth_logout from "./routes/api/auth/logout.ts";
import * as $api_auth_me from "./routes/api/auth/me.ts";
import * as $api_auth_register from "./routes/api/auth/register.ts";
import * as $api_events_id_ from "./routes/api/events/[id].ts";
import * as $api_events_id_approve from "./routes/api/events/[id]/approve.ts";
import * as $api_events_id_attendees from "./routes/api/events/[id]/attendees.ts";
import * as $api_events_id_cancel from "./routes/api/events/[id]/cancel.ts";
import * as $api_events_id_delete from "./routes/api/events/[id]/delete.ts";
import * as $api_events_id_signup from "./routes/api/events/[id]/signup.ts";
import * as $api_events_index from "./routes/api/events/index.ts";
import * as $api_events_upcoming from "./routes/api/events/upcoming.ts";
import * as $api_members_id_ from "./routes/api/members/[id].ts";
import * as $api_members_id_approve from "./routes/api/members/[id]/approve.ts";
import * as $api_members_id_reject from "./routes/api/members/[id]/reject.ts";
import * as $api_members_index from "./routes/api/members/index.ts";
import * as $api_members_pending from "./routes/api/members/pending.ts";
import * as $api_prs_id_ from "./routes/api/prs/[id].ts";
import * as $api_prs_id_approve from "./routes/api/prs/[id]/approve.ts";
import * as $api_prs_id_delete from "./routes/api/prs/[id]/delete.ts";
import * as $api_prs_index from "./routes/api/prs/index.ts";
import * as $api_prs_pending from "./routes/api/prs/pending.ts";
import * as $api_results_id_ from "./routes/api/results/[id].ts";
import * as $api_results_id_approve from "./routes/api/results/[id]/approve.ts";
import * as $api_results_id_delete from "./routes/api/results/[id]/delete.ts";
import * as $api_results_index from "./routes/api/results/index.ts";
import * as $api_results_pending from "./routes/api/results/pending.ts";
import * as $api_signups_id_ from "./routes/api/signups/[id].ts";
import * as $api_signups_index from "./routes/api/signups/index.ts";
import * as $api_wod_scores_id_approve from "./routes/api/wod-scores/[id]/approve.ts";
import * as $api_wod_scores_id_delete from "./routes/api/wod-scores/[id]/delete.ts";
import * as $api_wods_id_delete from "./routes/api/wods/[id]/delete.ts";
import * as $api_wods_id_scores from "./routes/api/wods/[id]/scores.ts";
import * as $api_wods_index from "./routes/api/wods/index.ts";
import * as $index from "./routes/index.tsx";
import * as $AdminSection from "./islands/AdminSection.tsx";
import * as $EventsSection from "./islands/EventsSection.tsx";
import * as $Hero from "./islands/Hero.tsx";
import * as $LeaderboardSection from "./islands/LeaderboardSection.tsx";
import * as $MemberAuth from "./islands/MemberAuth.tsx";
import * as $MembersSection from "./islands/MembersSection.tsx";
import * as $TabNavigation from "./islands/TabNavigation.tsx";
import * as $WodSection from "./islands/WodSection.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
    "./routes/_middleware.ts": $_middleware,
    "./routes/api/admin/login.ts": $api_admin_login,
    "./routes/api/admin/logout.ts": $api_admin_logout,
    "./routes/api/admin/reset-init.ts": $api_admin_reset_init,
    "./routes/api/admin/members/[id]/approve.ts": $api_admin_members_id_approve,
    "./routes/api/admin/prs/[id]/approve.ts": $api_admin_prs_id_approve,
    "./routes/api/admin/results/[id]/approve.ts": $api_admin_results_id_approve,
    "./routes/api/auth/change-password.ts": $api_auth_change_password,
    "./routes/api/auth/login.ts": $api_auth_login,
    "./routes/api/auth/logout.ts": $api_auth_logout,
    "./routes/api/auth/me.ts": $api_auth_me,
    "./routes/api/auth/register.ts": $api_auth_register,
    "./routes/api/events/[id].ts": $api_events_id_,
    "./routes/api/events/[id]/approve.ts": $api_events_id_approve,
    "./routes/api/events/[id]/attendees.ts": $api_events_id_attendees,
    "./routes/api/events/[id]/cancel.ts": $api_events_id_cancel,
    "./routes/api/events/[id]/delete.ts": $api_events_id_delete,
    "./routes/api/events/[id]/signup.ts": $api_events_id_signup,
    "./routes/api/events/index.ts": $api_events_index,
    "./routes/api/events/upcoming.ts": $api_events_upcoming,
    "./routes/api/members/[id].ts": $api_members_id_,
    "./routes/api/members/[id]/approve.ts": $api_members_id_approve,
    "./routes/api/members/[id]/reject.ts": $api_members_id_reject,
    "./routes/api/members/index.ts": $api_members_index,
    "./routes/api/members/pending.ts": $api_members_pending,
    "./routes/api/prs/[id].ts": $api_prs_id_,
    "./routes/api/prs/[id]/approve.ts": $api_prs_id_approve,
    "./routes/api/prs/[id]/delete.ts": $api_prs_id_delete,
    "./routes/api/prs/index.ts": $api_prs_index,
    "./routes/api/prs/pending.ts": $api_prs_pending,
    "./routes/api/results/[id].ts": $api_results_id_,
    "./routes/api/results/[id]/approve.ts": $api_results_id_approve,
    "./routes/api/results/[id]/delete.ts": $api_results_id_delete,
    "./routes/api/results/index.ts": $api_results_index,
    "./routes/api/results/pending.ts": $api_results_pending,
    "./routes/api/signups/[id].ts": $api_signups_id_,
    "./routes/api/signups/index.ts": $api_signups_index,
    "./routes/api/wod-scores/[id]/approve.ts": $api_wod_scores_id_approve,
    "./routes/api/wod-scores/[id]/delete.ts": $api_wod_scores_id_delete,
    "./routes/api/wods/[id]/delete.ts": $api_wods_id_delete,
    "./routes/api/wods/[id]/scores.ts": $api_wods_id_scores,
    "./routes/api/wods/index.ts": $api_wods_index,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/AdminSection.tsx": $AdminSection,
    "./islands/EventsSection.tsx": $EventsSection,
    "./islands/Hero.tsx": $Hero,
    "./islands/LeaderboardSection.tsx": $LeaderboardSection,
    "./islands/MemberAuth.tsx": $MemberAuth,
    "./islands/MembersSection.tsx": $MembersSection,
    "./islands/TabNavigation.tsx": $TabNavigation,
    "./islands/WodSection.tsx": $WodSection,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
